### ISSUE TITLE
Make `internal` enabled by default with flag

### ISSUE THREAD

**Issue by gitirabassi** [influxdata/telegraf-operator#10]
_Describe the issue here._

Right now, if you want to add the `internal` input plugin you need to add the annotation to every single deployment

I'd like to add a deployment flag like `--enable-default-internal-plugin=true` in which every telegraf will have `internal` plugin enabled by default

**Comment by wojciechka** [comment]
I am not sure this is the best way to do it.

I believe it would be better to allow configuring settings such as this one at a namespace level.

We can add a flag for now and extend it with namespace-specific setting later on.

WDYT?

**Comment by gitirabassi** [comment]
I don't know of any operator which makes use of "namespace specific configurations".

People can only use it on a deployment basis with annotations
When more people start using it we'll have a better understanding of their needs. 

I don't think we'll need the namespace configuration internally in Influxdata
