### ISSUE TITLE
I can't find how to mount a volume?

### ISSUE THREAD

**Issue by wonderful-ya** [influxdata/telegraf-operator#103]
_Describe the issue here._

I need **mount a dir** of own container to telegraf container in the Pod **by emptyDir volume**.
But I can't find the annotations for this condition.

is there have the suitable annotations for this condition?

##### What products and version are you using?
latest version

**Comment by wojciechka** [comment]
Hi,

It's not currently possible, but definitely seems like something worth looking into.

There's #80 that was created some time ago, but unfortunately the PR was never finished. Perhaps you would be interested in trying to add it based on that PR?

**Comment by wonderful-ya** [comment]
thanks for your answer

our project need this function,
today I forked this repo and
made same modify for volume mount.

the changes is uesed by our project now, I am working on test it.

hope it can work tomorrow, 
if it test pass, I will propose the pull request.
