### ISSUE TITLE
production-like deployment

### ISSUE THREAD

**Issue by vavdoshka** [influxdata/telegraf-operator#38]
Hello  @gitirabassi @wojciechka @goller @russorat
Could you please share your vision about getting this operator to a production-ready state? 
What is missing currently?

**Comment by gitirabassi** [comment]
Hello @vavdoshka we are currently running telelegraf-operator in production for months

please try it out

We even have a helm chart which makes things quite easy https://hub.helm.sh/charts/influxdata/telegraf-operator

**Comment by vavdoshka** [comment]
okay, thank you @gitirabassi!

BTW, in this case, it make sense to update the README so that people would see they can start using it.
