### ISSUE TITLE
Container Image: Latest is out of date

### ISSUE THREAD

**Issue by BondAnthony** [influxdata/telegraf-operator#48]
When a release is made the latest image in not updated. Latest currently points to image `v1.0.6`, I think we need to revisit the image build process and settle on a multi-version tag process.

Maybe something like this?

```
image_templates:
    - "quay.io/influxdb/telegraf-operator:latest"
    - "quay.io/influxdb/telegraf-operator:{{ .Tag }}"
    - "quay.io/influxdb/telegraf-operator:v{{ .Major }}"
    - "quay.io/influxdb/telegraf-operator:v{{ .Major }}.{{ .Minor }}"
```

**Comment by cbos** [comment]
@wojciechka 
The `latest` tag points to v1.0.6 as mentioned above.
The example deployment in `deployment/dev.yml' uses latest, but that is not working with the latest Telegraf operator. 

Can you label the latest image with latest?

**Comment by wojciechka** [comment]
@cbos Thank you for bumping the issue. We were aware of this, but somehow never got around to fixing it.

#72 will fix this once we also make a new release of telegraf-operator, which will also ensure future versions work as expected

**Comment by wojciechka** [comment]
The `latest` tag now points at [v1.3.2](https://github.com/influxdata/telegraf-operator/releases/tag/v1.3.2) and future releases will properly tag `latest` again.

Closing as this is now resolved.
