### ISSUE TITLE
Release 1.2.0?

### ISSUE THREAD

**Issue by ymatsiuk** [influxdata/telegraf-operator#56]
I've created https://github.com/influxdata/helm-charts/pull/319 for the future release and expected 87dc0575d790af1743596b48ba72d0869e09c53e to be released as `1.2.0`. Is there anything else expected to be delivered as well? Thanks in advance!

**Comment by ymatsiuk** [comment]
CC: @wojciechka @timhallinflux

**Comment by timhallinflux** [comment]
release has been tagged.
