### ISSUE TITLE
Issue(telegraf-operator): sidecar pods runs as root and should not

### ISSUE THREAD

**Issue by smark88** [influxdata/telegraf-operator#70]
When adding a `securityContext` to a deployment `runAsNonRoot: true`  telegraf will prevent the deployment from coming up since it runs as root and will need the Dockerfile to run as a non root user. This means that within any environment using the telegraph operator that all sidecar containers are running as Root. Which is very bad.

```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Warning  Failed     9m50s (x10 over 11m)  kubelet            Error: container has runAsNonRoot and image will run as root
  Normal   Pulled     82s (x49 over 11m)    kubelet            Container image "docker.io/library/telegraf:1.14" already present on machine
```

**Comment by wojciechka** [comment]
Telegraf-operator allows customizing the telegraf image to use in a sidecar - you can add `telegraf.influxdata.com/image` annotation and point to a container image that is non-root in this case.

So what you need is an alternate telegraf image that is not running as root.

I think you should open an issue for [telegraf](http://github.com/influxdata/telegraf) to create a non-root container image of telegraf alongside root telegraf and either move all sidecars to use non-root image or start by moving the deployments/statefulsets/... that have `runAsNonRoot: true` to use a different telegraf image.

I'm not sure what the implications of running as non-root image could be - i.e. if one or more telegraf input plugins that we use need root to gather their data.

**Comment by powersj** [comment]
Is it possible to have someone test out [my proposed change](https://github.com/influxdata/influxdata-docker/pull/536) to the Dockerfile running telegraf not as root?
