### ISSUE TITLE
Telegraf Operator should use a custom resource type instead of Secret

### ISSUE THREAD

**Issue by andrewchellis** [influxdata/telegraf-operator#71]
Running telegraf operator currently requires a cluster role with full permissions for secrets for any targeted namespaces within a k8s cluster.

The issues:
1. Requiring full permissions for all secrets for all namespaces is not acceptable from a data security perspective, these permissions are far beyond what the application should require
2. Programmatically generated objects pollute the user view of `secrets`

A custom, namespaced resource type like `TelegrafConfig` would keep this application data out of the user view and provide for much more reasonable permissioning for `telegraf-operator`

**Comment by wojciechka** [comment]
I'll close the issue, but we'll definitely think about other ways to achieve this.

We are considering using a single, namespace-specific secret (and at that point the ClusterRole could be much more specific regarding secrets), but that would require a rewrite of our secret handling logic.

Thanks for the feedback, though, limiting what operators can do in clusters is an important part, it's just not easy to do in this case, but will definitely be on our radar when planning refactoring of the code.
